In [40]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import chirp, find_peaks, peak_widths
from qutip import *
import time

In [45]:
# figure out how tensor products work 

cav_max = 3

qbit0 = basis(cav_max, n=1)
qbit1 = basis(cav_max, n=2)

print('qbit0: ', qbit0)
print('qbit1: ', qbit1)

qbit0:  Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]]
qbit1:  Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]]


In [42]:
cav_max = 3

qbit0 = basis(cav_max, n=0)
qbit1 = basis(cav_max, n=2)

tnsr = tensor(qbit0, qbit1)

# which rows encode for n = 2 tens qbit1 ; qbit0 tens n = 2

'''
======
(0, 1, 0) tensor (1, 0, 0) works like 

0 *(1, 
    0, 
    0)
    
1 *(1, ==> (0,0,0 | 1,0,0 | 0,0,0) ==> n1 = 1 and n2 = 0 
    0, 
    0)
    
0 *(1, 
    0, 
    0)

=======
allowed: (n1, n2): (0,0), (0,1), (1,0), (1,1), (0,2), (2,0)
not allowed: (1,2), (2,1), (2,2) ==> (0,0,0, 0,0,0, 0,*,*)
if eliminate last state ==> (0, 0, 0 | 0, 0, 0 | 0 - -)
'''

print(tnsr)

Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [48]:
# lets try it on operators

cav_max = 3

qbit0 = basis(cav_max, n=0)
qbit1 = basis(cav_max, n=0)

tnsr = tensor(qbit0, qbit1)

a = destroy(cav_max)
a = tensor(a, a)

a_dag = a.dag()

a_dag

Quantum object: dims = [[3, 3], [3, 3]], shape = (9, 9), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [1.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         1.41421356 0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         1.41421356 0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         2.         0.
  0.         0.         0.        ]]

In [50]:
# eliminate last state 

proj_tnsr = tnsr.eliminate_states([8], normalize=False)
print(proj_tnsr)

proj_adag = a_dag.eliminate_states([8], normalize=True)
#proj_adag

proj_adag*proj_adag*proj_tnsr

# adag * qeye , qeye * adag
# (0, 0) -> (1, 1)  -> (2, 2) == NULL

Quantum object: dims = [[8], [1]], shape = (8, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


Quantum object: dims = [[8], [1]], shape = (8, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [ ]:
# It works!!!